/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class PalindromeCheckerTest {

    private PalindromeChecker classUnderTest;

    @Before
    public void setUp() {
        classUnderTest = new PalindromeChecker();
    }

    @Test
    public void testCheckPalindrome_True() {

        assertTrue(classUnderTest.checkPalindrome("ANNA"));
    }

    @Test
    public void testCheckPalindrome_False() {
        assertFalse(classUnderTest.checkPalindrome("TESTING THIS STRING %+"));
    }

    @Test
    public void testCheckPalindrome_Empty() {
        assertFalse(classUnderTest.checkPalindrome(""));
    }

    @Test
    public void testReverseString() {
        assertEquals("+% GNIRTS SIHT GNITSET", classUnderTest.reverseString("TESTING THIS STRING %+"));
    }

    @Test
    public void testReverseString_Empty() {
        assertEquals("", classUnderTest.reverseString(""));
    }

    @Test
    public void testEqualStringsNotEmpty() {
        assertFalse(classUnderTest.equalStrings("TESTING THIS STRING %+", "+% GNIRTS SIHT GNITSET"));
    }

    @Test
    public void testEqualStringsNotEmpty_EmptyBoth() {
        assertFalse(classUnderTest.equalStrings("", ""));
    }

    @Test
    public void testEqualStringsNotEmpty_EmptyOriginal() {
        assertFalse(classUnderTest.equalStrings("AA", ""));
    }

    @Test
    public void testEqualStringsNotEmpty_EmptyReverse() {
        assertFalse(classUnderTest.equalStrings("", "AA"));
    }

    @Test
    public void testEqualStringsNotEmpty_Same() {
        assertTrue(classUnderTest.equalStrings("TESTING THIS STRING %+", "TESTING THIS STRING %+"));
    }
}
