/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Scanner in = new Scanner(System.in);
        PalindromeChecker checker = new PalindromeChecker();
        while(true) {
            String original = in.nextLine();
            if (original.equals("exit")) {
                break;
            } else if (!checker.checkPalindrome(original)) {
                System.out.println("It's a palindrome");
            } else {
                System.out.println("It's NOT a palindrome, sorry!");
            }
        }
    }
}
