/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

public class Solution {

    public boolean checkPalindrome(String original) {
        String reverse = reverseString(original);
        System.out.println(reverse);
        return equalStrings(original, reverse);  //Ctrl+Alt+N or Option+Command+N to Inline!
    }

    /**
     * Reverses the input string.
     * @param original The original String to be reversed
     * @return The reversed String
     */
    public String reverseString(String original) {
        StringBuilder builder = new StringBuilder();
        builder.append(original);
        return builder.reverse().toString();
    }

    /**
     * Compare two string if they are the same, if they are empty return false, empty string can't be a palindrome.
     * @param original String from user input
     * @param reverse String after reversal
     * @return true if original and reverse are equal and not empty.
     */
    public boolean equalStrings(String original, String reverse) {
        if (original.isEmpty() || reverse.isEmpty()) {
            return false;
        }
        return original.equals(reverse);
    }
}
